import { render, screen } from "@testing-library/react";
import { ChannelsComponent } from "../../../resources/components/ChannelsComponent";

describe('ChannelsComponent', () => {

  // Renders a list of channels with their respective images and numbers.
  it('should render channels with images and numbers', () => {
    // Arrange
    const channels = [
      {
        "id": "35357",
        "number": "3",
        "name": "CANAL 3 GT",
        "hd": false,
        "image": "https:\/\/clarovideocdn8.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SS\/CANAL3GT_t-290x163.png",
        "group_id": "889020",
        "liveref": "sv.CANAL3NACIONAL",
        "epg_url": "TV",
        "source_uri": "",
        "provider_metadata_id": 2,
        "provider_metadata_name": "NAGRA",
        "group": {
          "common": {
            "id": "889020",
            "title": "CANAL 3 GT",
            "title_episode": null,
            "title_uri": "CANAL-3-GT",
            "title_original": "CANAL 3 GT",
            "description": "CANAL 3 GT IPTV GUATEMALA",
            "description_large": "CANAL 3 GT",
            "short_description": null,
            "image_large": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SS\/CANAL3GTWHORIZONTAL.jpg?size=675x380",
            "image_medium": "https:\/\/clarovideocdn0.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SS\/CANAL3GTWVERTICAL.jpg?size=200x300",
            "image_small": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SS\/CANAL3GTWHORIZONTAL.jpg?size=290x163",
            "image_still": null,
            "image_background": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/CLEAN\/CANAL3GT_e-1280x720.jpg",
            "url_imagen_t1": "https:\/\/clarovideocdn3.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/CLEAN\/CANAL3GTWVERTICAL.jpg?size=200x300",
            "url_imagen_t2": "https:\/\/clarovideocdn5.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/CLEAN\/CANAL3GTWHORIZONTAL.jpg?size=290x163",
            "image_base_horizontal": "https:\/\/clarovideocdn9.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SS\/CANAL3GTWHORIZONTAL.jpg",
            "image_base_vertical": "https:\/\/clarovideocdn7.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SS\/CANAL3GTWVERTICAL.jpg",
            "image_base_square": "https:\/\/clarovideocdn7.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SS\/CANAL3GTWCUADRADO.jpg",
            "image_clean_horizontal": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/CLEAN\/CANAL3GTWHORIZONTAL.jpg",
            "image_clean_vertical": "https:\/\/clarovideocdn0.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/CLEAN\/CANAL3GTWVERTICAL.jpg",
            "image_clean_square": "https:\/\/clarovideocdn0.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/CLEAN\/CANAL3GTWCUADRADO.jpg",
            "image_sprites": "https:\/\/clarovideocdn3.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SPRITES\/CANAL3GT-SPRITEBAR.jpg",
            "image_frames": "https:\/\/clarovideocdn9.clarovideo.net\/CVPERU\/PELICULAS\/CANAL3GT\/EXPORTACION_WEB\/SPRITES\/CANAL3GT-00h-00m-00s-00f.jpg",
            "image_trickplay": "",
            "image_external": null,
            "duration": null,
            "date": "15\/07\/2020",
            "year": null,
            "preview": "false",
            "season_number": null,
            "episode_number": null,
            "format_types": "susc",
            "live_enabled": "1",
            "live_type": "1",
            "live_ref": "sv.CANAL3NACIONAL",
            "source_uri": "",
            "timeshift": "4000",
            "votes_average": 4,
            "rating_code": "G",
            "proveedor_name": "CLARO VIDEO PERU",
            "proveedor_code": "cvperu",
            "encoder_tecnology": {
              "id": "3",
              "desc": "HARMONIC_VOS"
            },
            "recorder_technology": {
              "id": "4",
              "desc": "HARMONIC_VOS"
            },
            "resource_name": null,
            "rollingcreditstime": null,
            "rollingcreditstimedb": null,
            "is_series": false,
            "channel_number": "3"
          }
        },
        "events": [
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355744",
            "name": "Esta Historia Me Suena",
            "description": "Esta Historia Me Suena",
            "talent": null,
            "date_begin": "2024\/03\/22 14:00:00",
            "date_end": "2024\/03\/22 15:00:00",
            "unix_begin": 1711137600,
            "unix_end": 1711141200,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "ac5a95f23d13",
            "ext_ncont_id": "350745469184",
            "ext_nevt_id": "ac5a95f23d13",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Esta Historia Me Suena",
            "ext_ep_original_name": null,
            "ext_series_id": "350745456683",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "Todos",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355752",
            "name": "Mujer Casos De La Vida Real",
            "description": "Mujer Casos de la Vida Real",
            "talent": null,
            "date_begin": "2024\/03\/22 15:00:00",
            "date_end": "2024\/03\/22 16:00:00",
            "unix_begin": 1711141200,
            "unix_end": 1711144800,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "78d6bd1d977c",
            "ext_ncont_id": "120835692025",
            "ext_nevt_id": "78d6bd1d977c",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Mujer Casos De La Vida Real",
            "ext_ep_original_name": null,
            "ext_series_id": "120835679524",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355760",
            "name": "Me Robó Mi Vida",
            "description": "Me Robó Mi Vida",
            "talent": null,
            "date_begin": "2024\/03\/22 16:00:00",
            "date_end": "2024\/03\/22 17:00:00",
            "unix_begin": 1711144800,
            "unix_end": 1711148400,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "9ef08549e694",
            "ext_ncont_id": "212315124931",
            "ext_nevt_id": "9ef08549e694",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Me Robó Mi Vida",
            "ext_ep_original_name": null,
            "ext_series_id": "212315112430",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355768",
            "name": "La Familia De Mi Esposo",
            "description": "Una familia tradicional turca cuyo hijo desapareció hace años y Tarik, quien perdió a su esposa, se vuelven vecinos.",
            "talent": null,
            "date_begin": "2024\/03\/22 17:00:00",
            "date_end": "2024\/03\/22 18:00:00",
            "unix_begin": 1711148400,
            "unix_end": 1711152000,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "a34c6be7208d",
            "ext_ncont_id": "334403409700",
            "ext_nevt_id": "a34c6be7208d",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "La Familia De Mi Esposo",
            "ext_ep_original_name": null,
            "ext_series_id": "334403397199",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355776",
            "name": "María Mercedes",
            "description": "Una humilde y joven vendedora de lotería trabaja para sacar adelante a su familia y se enamora perdidamente de un hombre rico.",
            "talent": null,
            "date_begin": "2024\/03\/22 18:00:00",
            "date_end": "2024\/03\/22 19:00:00",
            "unix_begin": 1711152000,
            "unix_end": 1711155600,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "9115e37044f0",
            "ext_ncont_id": "783900656251",
            "ext_nevt_id": "9115e37044f0",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "María Mercedes",
            "ext_ep_original_name": null,
            "ext_series_id": "783900643750",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355784",
            "name": "Telediario Nocturno",
            "description": "Telediario Nocturno",
            "talent": null,
            "date_begin": "2024\/03\/22 19:00:00",
            "date_end": "2024\/03\/22 20:00:00",
            "unix_begin": 1711155600,
            "unix_end": 1711159200,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "b7c6d1457821",
            "ext_ncont_id": "4441523956",
            "ext_nevt_id": "b7c6d1457821",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Telediario Nocturno",
            "ext_ep_original_name": null,
            "ext_series_id": "004441511455",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355792",
            "name": "El Rey, Vicente Fernandez",
            "description": "Desde su humilde infancia hasta el estrellato, la historia de la vertiginosa vida y carrera del cantautor mexicano Vicente Fernández, narrada a lo largo de siete décadas.",
            "talent": null,
            "date_begin": "2024\/03\/22 20:00:00",
            "date_end": "2024\/03\/22 22:00:00",
            "unix_begin": 1711159200,
            "unix_end": 1711166400,
            "duration": "02:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "29843cd00123",
            "ext_ncont_id": "922633412571",
            "ext_nevt_id": "29843cd00123",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "El Rey, Vicente Fernandez",
            "ext_ep_original_name": null,
            "ext_series_id": "922633400070",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355800",
            "name": "Cukur",
            "description": "La familia mafiosa Koçoval? gobierna bajo sus reglas el vecindario de Çukur, una de las zonas más riesgosas de Estambul.",
            "talent": null,
            "date_begin": "2024\/03\/22 22:00:00",
            "date_end": "2024\/03\/22 23:00:00",
            "unix_begin": 1711166400,
            "unix_end": 1711170000,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "44499ed75d2b",
            "ext_ncont_id": "171441642122",
            "ext_nevt_id": "44499ed75d2b",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Cukur",
            "ext_ep_original_name": null,
            "ext_series_id": "171441629621",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35357",
            "source_uri": "",
            "id": "1977355808",
            "name": "Criminal Minds",
            "description": "Criminal Minds",
            "talent": null,
            "date_begin": "2024\/03\/22 23:00:00",
            "date_end": "2024\/03\/23 06:00:00",
            "unix_begin": 1711170000,
            "unix_end": 1711195200,
            "duration": "07:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "a6457ac6b7c9",
            "ext_ncont_id": "951351155636",
            "ext_nevt_id": "a6457ac6b7c9",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Criminal Minds",
            "ext_ep_original_name": null,
            "ext_series_id": "951351143035",
            "ext_season_id": "12",
            "ext_episode_id": "601",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          }
        ]
      },
      {
        "id": "35358",
        "number": "7",
        "name": "CANAL 7 GT",
        "hd": false,
        "image": "https:\/\/clarovideocdn8.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SS\/CANAL7GT_t-290x163.png",
        "group_id": "889053",
        "liveref": "sv.CANAL7NACIONAL",
        "epg_url": "TV",
        "source_uri": "",
        "provider_metadata_id": 2,
        "provider_metadata_name": "NAGRA",
        "group": {
          "common": {
            "id": "889053",
            "title": "CANAL 7 GT",
            "title_episode": null,
            "title_uri": "CANAL-7-GT",
            "title_original": "CANAL 7 GT",
            "description": "CANAL 7 GT",
            "description_large": "CANAL 7 GT",
            "short_description": null,
            "image_large": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SS\/CANAL7GTWHORIZONTAL.jpg?size=675x380",
            "image_medium": "https:\/\/clarovideocdn0.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SS\/CANAL7GTWVERTICAL.jpg?size=200x300",
            "image_small": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SS\/CANAL7GTWHORIZONTAL.jpg?size=290x163",
            "image_still": null,
            "image_background": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/CLEAN\/CANAL7GT_e-1280x720.jpg",
            "url_imagen_t1": "https:\/\/clarovideocdn3.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/CLEAN\/CANAL7GTWVERTICAL.jpg?size=200x300",
            "url_imagen_t2": "https:\/\/clarovideocdn5.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/CLEAN\/CANAL7GTWHORIZONTAL.jpg?size=290x163",
            "image_base_horizontal": "https:\/\/clarovideocdn9.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SS\/CANAL7GTWHORIZONTAL.jpg",
            "image_base_vertical": "https:\/\/clarovideocdn7.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SS\/CANAL7GTWVERTICAL.jpg",
            "image_base_square": "https:\/\/clarovideocdn7.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SS\/CANAL7GTWCUADRADO.jpg",
            "image_clean_horizontal": "https:\/\/clarovideocdn2.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/CLEAN\/CANAL7GTWHORIZONTAL.jpg",
            "image_clean_vertical": "https:\/\/clarovideocdn0.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/CLEAN\/CANAL7GTWVERTICAL.jpg",
            "image_clean_square": "https:\/\/clarovideocdn0.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/CLEAN\/CANAL7GTWCUADRADO.jpg",
            "image_sprites": "https:\/\/clarovideocdn3.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SPRITES\/CANAL7GT-SPRITEBAR.jpg",
            "image_frames": "https:\/\/clarovideocdn9.clarovideo.net\/CVPERU\/PELICULAS\/CANAL7GT\/EXPORTACION_WEB\/SPRITES\/CANAL7GT-00h-00m-00s-00f.jpg",
            "image_trickplay": "",
            "image_external": null,
            "duration": null,
            "date": "15\/07\/2020",
            "year": null,
            "preview": "false",
            "season_number": null,
            "episode_number": null,
            "format_types": "susc",
            "live_enabled": "1",
            "live_type": "1",
            "live_ref": "sv.CANAL7NACIONAL",
            "source_uri": "",
            "timeshift": "4000",
            "votes_average": 4,
            "rating_code": "G",
            "proveedor_name": "CLARO VIDEO PERU",
            "proveedor_code": "cvperu",
            "encoder_tecnology": {
              "id": "3",
              "desc": "HARMONIC_VOS"
            },
            "recorder_technology": {
              "id": "4",
              "desc": "HARMONIC_VOS"
            },
            "resource_name": null,
            "rollingcreditstime": null,
            "rollingcreditstimedb": null,
            "is_series": false,
            "channel_number": "7"
          }
        },
        "events": [
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355177",
            "name": "Perdóname",
            "description": "Osman Kasan es un exitoso hombre de negocios y uno de los empresarios más ricos de Ankara. Se caracteriza por ser un hombre severo y cruel, obsesionado con una disciplina que hace infeliz a su familia.",
            "talent": null,
            "date_begin": "2024\/03\/22 14:00:00",
            "date_end": "2024\/03\/22 15:00:00",
            "unix_begin": 1711137600,
            "unix_end": 1711141200,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "83c4680a9b0d",
            "ext_ncont_id": "334130675128",
            "ext_nevt_id": "83c4680a9b0d",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Perdóname",
            "ext_ep_original_name": null,
            "ext_series_id": "334130662627",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355188",
            "name": "Vencer La Culpa",
            "description": "Los destinos de cuatro mujeres de distintas edades y niveles socioeconómicos se entrelazan debido a la desaparición de una misteriosa joven. En el proceso para encontrarla, varios secretos salen a la luz.",
            "talent": null,
            "date_begin": "2024\/03\/22 15:00:00",
            "date_end": "2024\/03\/22 16:00:00",
            "unix_begin": 1711141200,
            "unix_end": 1711144800,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "5ad28e9eb067",
            "ext_ncont_id": "101213397423",
            "ext_nevt_id": "5ad28e9eb067",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Vencer La Culpa",
            "ext_ep_original_name": null,
            "ext_series_id": "101213384922",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355199",
            "name": "Como Dice El Dicho",
            "description": "La serie narra diversas historias donde se selecciona un dicho y una temática que se aplican a situaciones de la vida.",
            "talent": null,
            "date_begin": "2024\/03\/22 16:00:00",
            "date_end": "2024\/03\/22 17:00:00",
            "unix_begin": 1711144800,
            "unix_end": 1711148400,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "082250545f5c",
            "ext_ncont_id": "255741242636",
            "ext_nevt_id": "082250545f5c",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Como Dice El Dicho",
            "ext_ep_original_name": null,
            "ext_series_id": "255741230135",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355210",
            "name": "Caso Cerrado",
            "description": "La doctora Ana María Polo interviene en batallas legales conmovedoras que afectan a los latinos.",
            "talent": null,
            "date_begin": "2024\/03\/22 17:00:00",
            "date_end": "2024\/03\/22 18:00:00",
            "unix_begin": 1711148400,
            "unix_end": 1711152000,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "b006a29f88eb",
            "ext_ncont_id": "462711968166",
            "ext_nevt_id": "b006a29f88eb",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Caso Cerrado",
            "ext_ep_original_name": null,
            "ext_series_id": "462711955664",
            "ext_season_id": "12",
            "ext_episode_id": "502",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355221",
            "name": "Dr. Milagro",
            "description": "Un joven doctor que padece el síndrome del sabio se une al equipo de cirugía de un hospital.",
            "talent": null,
            "date_begin": "2024\/03\/22 18:00:00",
            "date_end": "2024\/03\/22 19:00:00",
            "unix_begin": 1711152000,
            "unix_end": 1711155600,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "09ba36a0da5c",
            "ext_ncont_id": "790513043881",
            "ext_nevt_id": "09ba36a0da5c",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Dr. Milagro",
            "ext_ep_original_name": null,
            "ext_series_id": "790513031380",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355232",
            "name": "La Rosa De Guadalupe",
            "description": "Vive día a día una nueva historia de fe, inspirada en los milagros de la virgen de Guadalupe.",
            "talent": null,
            "date_begin": "2024\/03\/22 19:00:00",
            "date_end": "2024\/03\/22 20:00:00",
            "unix_begin": 1711155600,
            "unix_end": 1711159200,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "cc382a0a14b9",
            "ext_ncont_id": "914888028286",
            "ext_nevt_id": "cc382a0a14b9",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "La Rosa De Guadalupe",
            "ext_ep_original_name": null,
            "ext_series_id": "914888015785",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355243",
            "name": "Elif",
            "description": "Melek se enamora de Kenan, el hijo favorito de la familia para la que trabajaba. Pero la madre de Kenan la rechaza y la envía lejos a pesar de estar embarazada.",
            "talent": null,
            "date_begin": "2024\/03\/22 20:00:00",
            "date_end": "2024\/03\/22 21:00:00",
            "unix_begin": 1711159200,
            "unix_end": 1711162800,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "0024c02d7d57",
            "ext_ncont_id": "43744589796",
            "ext_nevt_id": "0024c02d7d57",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Elif",
            "ext_ep_original_name": null,
            "ext_series_id": "043744577295",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355254",
            "name": "Fugitiva",
            "description": "Una mujer es vendida como esclava durante su adolescencia a un violento hombre de negocios. Años más tarde, aprovecha la llegada de unos invitados a la casa para escapar junto con su hijo.",
            "talent": null,
            "date_begin": "2024\/03\/22 21:00:00",
            "date_end": "2024\/03\/22 22:00:00",
            "unix_begin": 1711162800,
            "unix_end": 1711166400,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "393d3f0d057a",
            "ext_ncont_id": "220433613192",
            "ext_nevt_id": "393d3f0d057a",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Fugitiva",
            "ext_ep_original_name": null,
            "ext_series_id": "220433600691",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355265",
            "name": "Noti 7 Nocturno",
            "description": "Presentamos la actualidad de Guatemala y el mundo en este espacio informativo. Conoce los sucesos, datos de economía, salud, lo que ocurre en política, lo último en tecnología, cultura, reportajes, cocina y deportes.",
            "talent": null,
            "date_begin": "2024\/03\/22 22:00:00",
            "date_end": "2024\/03\/22 23:00:00",
            "unix_begin": 1711166400,
            "unix_end": 1711170000,
            "duration": "01:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "4014ae7cabdf",
            "ext_ncont_id": "300324272023",
            "ext_nevt_id": "4014ae7cabdf",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Noti 7 Nocturno",
            "ext_ep_original_name": null,
            "ext_series_id": "300324259522",
            "ext_season_id": "12",
            "ext_episode_id": "501",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          },
          {
            "channel_id": "35358",
            "source_uri": "",
            "id": "1977355276",
            "name": "Primer Impacto",
            "description": "Espacio informativo en el que se muestran contenidos fuertes e imágenes espectaculares, poniendo un énfasis especial en aquellos sucesos de naturaleza cruda, controversial y polémica.",
            "talent": null,
            "date_begin": "2024\/03\/22 23:00:00",
            "date_end": "2024\/03\/23 06:00:00",
            "unix_begin": 1711170000,
            "unix_end": 1711195200,
            "duration": "07:00:00",
            "language": "esp",
            "type": "0",
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": "609ce097e7da",
            "ext_ncont_id": "447314130723",
            "ext_nevt_id": "609ce097e7da",
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": "Primer Impacto",
            "ext_ep_original_name": null,
            "ext_series_id": "447314118122",
            "ext_season_id": "12",
            "ext_episode_id": "601",
            "ext_language": "spa",
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "",
            "ext_catchup": "1",
            "ext_startover": "1",
            "ext_recordable": "1",
            "parental_rating": "+12",
            "aud_stereo": "0",
            "aud_dolby": "0",
            "vid_black_and_white": "0",
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
          }
        ]
      },
    ];
    const setEvent = jest.fn();

    // Act
    render(<ChannelsComponent channels={channels} setEvent={setEvent} />);

    // Assert
    expect(screen.getByText('HOY')).toBeInTheDocument();
  });

  // The channels list is empty, no channels are rendered.
  it('should not render any channels when the list is empty', () => {
    // Arrange
    const channels = [];
    const setEvent = jest.fn();

    // Act
    render(<ChannelsComponent channels={channels} setEvent={setEvent} />);

    // Assert
    expect(screen.queryByText('Channel 1')).not.toBeInTheDocument();
    expect(screen.queryByText('Channel 2')).not.toBeInTheDocument();
    expect(screen.queryByAltText('Channel 1')).not.toBeInTheDocument();
    expect(screen.queryByAltText('Channel 2')).not.toBeInTheDocument();
  });
});